name: yts_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+5

environment:
    sdk: '>=3.0.0'

dependencies:
    adaptive_action_sheet: ^2.0.2
    assets_audio_player:
        git:
            url: https://github.com/benjitusk/Flutter-AssetsAudioPlayer.git
    audio_service: ^0.18.9
    audio_video_progress_bar: ^1.0.1
    audioplayers: ^4.0.1
    cached_network_image: ^3.2.3
    carousel_slider: ^4.2.1
    cloud_firestore: ^4.4.3
    cloud_functions: ^4.0.12
    collection: ^1.17.0
    firebase_analytics: ^10.5.1
    firebase_app_check: ^0.1.1+14
    firebase_auth: ^4.2.9
    firebase_core: ^2.7.0
    firebase_dynamic_links: ^5.3.1
    firebase_messaging: ^14.6.9
    firebase_storage: ^11.0.14
    flutter:
        sdk: flutter
    flutter_markdown: ^0.6.14
    get_it: ^7.2.0
    google_api_availability: ^5.0.0
    intl: ^0.17.0
    just_audio: ^0.9.32
    package_info_plus: ^4.2.0
    safe_device: ^1.1.4
    shared_preferences: ^2.2.2
    text_scroll: ^0.2.0
    url_launcher: ^6.1.10

dev_dependencies:
    flutter_test:
        sdk: flutter
    # flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
