// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlc_OYJqpkis9_5zmQMf4FZ4f8d_s31Og',
    appId: '1:3976870161:android:b6843da7e4bfc1540d74b0',
    messagingSenderId: '3976870161',
    projectId: 'yeshivat-torat-shraga',
    databaseURL: 'https://yeshivat-torat-shraga-default-rtdb.firebaseio.com',
    storageBucket: 'yeshivat-torat-shraga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIYlSE0mRHxyTILjup8BEvPZz35z4qsA',
    appId: '1:3976870161:ios:cc657b3b144a3e7c0d74b0',
    messagingSenderId: '3976870161',
    projectId: 'yeshivat-torat-shraga',
    databaseURL: 'https://yeshivat-torat-shraga-default-rtdb.firebaseio.com',
    storageBucket: 'yeshivat-torat-shraga.appspot.com',
    iosClientId: '3976870161-9c4hbmni8av1jl1clfgpoo7b59855aun.apps.googleusercontent.com',
    iosBundleId: 'com.benjitusk.YTS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIYlSE0mRHxyTILjup8BEvPZz35z4qsA',
    appId: '1:3976870161:ios:cc657b3b144a3e7c0d74b0',
    messagingSenderId: '3976870161',
    projectId: 'yeshivat-torat-shraga',
    databaseURL: 'https://yeshivat-torat-shraga-default-rtdb.firebaseio.com',
    storageBucket: 'yeshivat-torat-shraga.appspot.com',
    iosClientId: '3976870161-9c4hbmni8av1jl1clfgpoo7b59855aun.apps.googleusercontent.com',
    iosBundleId: 'com.benjitusk.YTS',
  );
}
